# Read Different File Formats in Python

In [4]:
import pandas as pd
# To display all the columns from datset
pd.pandas.set_option('display.max_columns',None)
# To display all the row from datset
pd.pandas.set_option('display.max_rows',None)

In [5]:
df = pd.read_table(r'data\allhypo.data', sep=',')
df.head()

,41,F,f,f.1,f.2,f.3,f.4,f.5,f.6,f.7,f.8,f.9,f.10,f.11,f.12,f.13,t,1.3,t.1,2.5,t.2,125,t.3,1.14,t.4,109,f.14,?,SVHC,negative.|3733
0,23,F,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,4.1,t,2,t,102,f,?,f,?,f,?,other,negative.|1442
1,46,M,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,0.98,f,?,t,109,t,0.91,t,120,f,?,other,negative.|2965
2,70,F,t,f,f,f,f,f,f,f,f,f,f,f,f,f,t,0.16,t,1.9,t,175,f,?,f,?,f,?,other,negative.|806
3,70,F,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,0.72,t,1.2,t,61,t,0.87,t,70,f,?,SVI,negative.|2807
4,18,F,t,f,f,f,f,f,f,f,f,f,f,f,f,f,t,0.03,f,?,t,183,t,1.3,t,141,f,?,other,negative.|3434